In [3]:
import numpy as np


In [5]:
a1 = np.array([7,8,6])
a2 = np.array([3,4,1])

In [9]:
a3=np.concatenate((a1,a2))
print(a3)

[7 8 6 3 4 1]


In [11]:
a1 = np.array([[7,8,6],[1,0,9]])
a2 = np.array([[3,4,1],[2,3,4]])

In [25]:
a3=np.hstack((a1,a2))
print(a3)

[[7 8 6 3 4 1]
 [1 0 9 2 3 4]]


In [1]:
import numpy as np


In [3]:
a1=np.array([11,22,33,44,55])
for v in a1:
    print(v)

11
22
33
44
55


In [21]:
a2=np.array([[[11,22,33],[77,88,99]],[[12,25,36],[52,62,42]]])
for v in a2:
    print(v)

[[11 22 33]
 [77 88 99]]
[[12 25 36]
 [52 62 42]]


In [33]:
for n in np.nditer(a2):
    print(n)

11
22
33
77
88
99
12
25
36
52
62
42


In [37]:
for n in np.nditer(a2[0,::2]):
    print(n)

11
22
33


In [31]:
for n in np.nditer(a1):
    print(n)

11
22
33
44
55
